CONTRACT_MAP = {
    "AEX": {"code": "AE", "cycle": "FGHJKMNQUVXZ", "exchange": "EuronextInd"},
    "ALUMINIUM": {"code": "AL", "cycle": "FGHJKMNQUVXZ", "exchange": "COMEX"},
    "ALUMINIUM_LME": {"code": "Q8", "cycle": "FGHJKMNQUVXZ", "exchange": "LME"},
    "AUD": {"code": "A6", "cycle": "HMUZ", "exchange": "CME"},
    "AUDJPY": {"code": "UK", "cycle": "HMUZ", "exchange": "CME"},
    "BB3M": {"code": "BR", "cycle": "HMUZ", "exchange": "CME"},
    "BBCOMM": {"code": "AH", "cycle": "HMUZ", "exchange": "CBOT"},
    "BEL20": {"code": "BE", "cycle": "FGHJKMNQUVXZ", "exchange": "EuronextInd"},
    "BITCOIN": {"code": "BA", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "BOBL": {"code": "HR", "cycle": "HMUZ", "exchange": "EUREX"},
    "BONO": {"code": "IZ", "cycle": "HMUZ", "exchange": "EUREX"},
    "BOVESPA": {"code": "IF", "cycle": "GJMQVZ", "exchange": "CME"},
    "BRE": {"code": "L6", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "BRENT": {"code": "QA", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "BRENT_W": {"code": "CB", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "BRENT-LAST": {"code": "TBZ", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "BTP": {"code": "II", "cycle": "HMUZ", "exchange": "EUREX"},
    "BTP3": {"code": "IA", "cycle": "HMUZ", "exchange": "EUREX"},
    "BUND": {"code": "GG", "cycle": "HMUZ", "exchange": "EUREX"},
    "BUTTER": {"code": "BD", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "BUXL": {"code": "GX", "cycle": "HMUZ", "exchange": "EUREX"},
    "CAC": {"code": "MX", "cycle": "FGHJKMNQUVXZ", "exchange": "EuronextInd"},
    "CAD": {"code": "D6", "cycle": "HMUZ", "exchange": "CME"},
    "CADJPY": {"code": "UF", "cycle": "HMUZ", "exchange": "CME"},
    "CAD10": {"code": "CG", "cycle": "HMUZ", "exchange": "TMX"},
    "CANOLA": {"code": "RS", "cycle": "FHKNX", "exchange": "ICE/CA"},
    "CH10": {"code": "CF", "cycle": "HMUZ", "exchange": "EUREX"},
    "CHEESE": {"code": "BJ", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "CHF": {"code": "S6", "cycle": "HMUZ", "exchange": "CME"},
    "CHFJPY": {"code": "UP", "cycle": "HMUZ", "exchange": "CME"},
    "CNH": {"code": "ZX", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/SG"},
    "CNH-onshore": {"code": "ZP", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/SG"},
    "COCOA_LDN": {"code": "CA", "cycle": "HKNUZ", "exchange": "ICE/EU/Com"},
    "COCOA_NY": {"code": "CC", "cycle": "HKNUZ", "exchange": "ICE/US"},
    "COFFEE": {"code": "KC", "cycle": "HKNUZ", "exchange": "ICE/US"},
    "COPPER": {"code": "HG", "cycle": "FHJMNUVZ", "exchange": "COMEX"},
    "COPPER-micro": {"code": "QL", "cycle": "HKNUZ", "exchange": "COMEX"},
    "CORN": {"code": "ZC", "cycle": "HKNUZ", "exchange": "CBOT"},
    "CORN-EURO": {"code": "XB", "cycle": "HMQX", "exchange": "EuronextCom"},
    "COTTON": {"code": "KG", "cycle": "HKNVZ", "exchange": "NYMEX"},
    "COTTON2": {"code": "CT", "cycle": "HKNVZ", "exchange": "ICE/US"},
    "CRUDE_ICE": {"code": "WI", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "CRUDE_W": {"code": "CL", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "CZK": {"code": "WC", "cycle": "HMUZ", "exchange": "CME"},
    "DAX": {"code": "DY", "cycle": "HMUZ", "exchange": "EUREX"},
    "DIVDAX-DIVI": {"code": "AI", "cycle": "HMUZ", "exchange": "EUREX"},
    "DJSTX-SMALL": {"code": "PT", "cycle": "HMUZ", "exchange": "EUREX"},
    "DOW": {"code": "YM", "cycle": "HMUZ", "exchange": "CBOT"},
    "DX": {"code": "DX", "cycle": "HMUZ", "exchange": "ICE/US"},
    "ETHANOL": {"code": "ZK", "cycle": "FGHJKMNQUVXZ", "exchange": "CBOT"},
    "ETHEREUM": {"code": "ER", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "EUA": {
        "code": "CK",
        "cycle": "FGHJKMNQUVXZ",
        "days_count": 800,
        "exchange": "ENDEX",
    },
    "EUR": {"code": "E6", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "EURAUD": {"code": "UC", "cycle": "HMUZ", "exchange": "CME"},
    "EURCAD": {"code": "EP", "cycle": "HMUZ", "exchange": "ICE/US"},
    "EURCHF": {"code": "RF", "cycle": "HMUZ", "exchange": "CME"},
    "EURGBP": {"code": "RP", "cycle": "HMUZ", "exchange": "CME"},
    "EURIBOR": {"code": "TV", "cycle": "HMUZ", "exchange": "EUREX"},
    "EURIBOR-ICE": {
        "code": "IM",
        "cycle": "HMUZ",
        "days_count": 800,
        "exchange": "ICE",
    },
    "EUROSTX": {"code": "FX", "cycle": "HMUZ", "exchange": "EUREX"},
    "EUROSTX-LARGE": {"code": "PF", "cycle": "HMUZ", "exchange": "EUREX"},
    "EUROSTX-SMALL": {"code": "PI", "cycle": "HMUZ", "exchange": "EUREX"},
    "EUROSTX200-LARGE": {"code": "PO", "cycle": "HMUZ", "exchange": "EUREX"},
    "EURO600": {"code": "FY", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-AUTO": {"code": "S5", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-BASIC": {"code": "UJ", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-BANKS": {"code": "FA", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-CONSTRUCTION": {"code": "DMM", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-DIV50": {"code": "DO", "cycle": "MZ", "exchange": "EUREX"},
    "EU-DIV30": {"code": "AQ", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-DJ-OIL": {"code": "D9", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-DJ-TECH": {"code": "UO", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-DJ-UTIL": {"code": "IE", "cycle": "HMUZ", "exchange": "EUREX"},
    'EU-FOOD': {'code': 'DMN', 'exchange': 'EUREX', 'cycle': 'HMUZ'}, 
    'EU-HOUSE': {'code': 'DMU', 'exchange': 'EUREX', 'cycle': 'HMUZ'}, 
    "EU-HEALTH": {"code": "YS", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-INSURE": {"code": "DML", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-MEDIA": {"code": "UQ", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-REALESTATE": {"code": "M4", "cycle": "HMUZ", "exchange": "EUREX"},
    'EU-RETAIL': {'code': 'DMT', 'exchange': 'EUREX', 'cycle': 'HMUZ'},
    "EU-OIL": {"code": "UH", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-TECH": {"code": "UO", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-TRAVEL": {"code": "J3", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-UTILS": {"code": "J4", "cycle": "HMUZ", "exchange": "EUREX"},
    "FANG": {"code": "FG", "cycle": "HMUZ", "exchange": "ICE/US"},
    "FED": {"code": "ZQ", "cycle": "FGHJKMNQUVXZ", "exchange": "CBOT"},
    "FEEDCOW": {"code": "GF", "cycle": "FHJKQUVX", "exchange": "CME"},
    "FTSE100": {"code": "X", "cycle": "HMUZ", "exchange": "ICE"},
    "FTSE250": {"code": "Y", "cycle": "HMUZ", "exchange": "ICE"},
    "FTSECHINAA": {"code": "HN", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},    
    "FTSETAIWAN": {"code": "T1", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "GAS-LAST": {"code": "HH", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GAS_NL": {"code": "TG", "cycle": "FGHJKMNQUVXZ", "exchange": "ENDEX"},
    "GAS_UK": {"code": "NF", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "GAS_US": {"code": "NG", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GAS_US_mini": {"code": "QG", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GASOIL": {"code": "LF", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "GASOILINE": {"code": "RB", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GAS-PEN": {"code": "HP", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GBP": {"code": "B6", "cycle": "HMUZ", "exchange": "CME"},
    "GBPCHF": {"code": "SS", "cycle": "HMUZ", "exchange": "ICE/US"},
    "GBPEUR": {"code": "RP", "cycle": "HMUZ", "exchange": "CME"},
    "GBPJPY": {"code": "UR", "cycle": "HMUZ", "exchange": "CME"},
    "GICS": {"code": "GD", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "GILT": {"code": "G", "cycle": "HMUZ", "exchange": "ICE"},
    "GOLD": {"code": "GC", "cycle": "FGHJKMNQUVXZ", "exchange": "COMEX"},
    "GOLD_micro": {"code": "GR", "cycle": "FGHJKMNQUVXZ", "exchange": "COMEX"},
    "HANG": {"code": "HS", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"},
    "HANGENT_mini": {"code": "IX", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"},
    "HANGTECH": {"code": "HI", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"},
    "HEATOIL": {"code": "HO", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "HEATOIL-ICE": {"code": "LO", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "HOUSE-US": {"code": "I6", "cycle": "FKQX", "exchange": "CME"},
    "IBEX": {"code": "EF", "cycle": "HMUZ", "exchange": "MEFF"},
    "IRON": {"code": "C0", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    #"INR": {"code": "U-", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "IRS": {"code": "WY", "cycle": "HMUZ", "exchange": "CME"},
    "JGB": {"code": "TJ", "cycle": "HMUZ", "exchange": "JPX"},
    "JGB-SGX-mini": {"code": "JX", "cycle": "HMUZ", "exchange": "SGX"},
    "JPY": {"code": "J6", "cycle": "HMUZ", "exchange": "CME"},
    "JP-REALESTATE": {"code": "V.", "cycle": "HMUZ", "exchange": "JPX"},
    "JSE40": {"code": "LX", "cycle": "HMUZ", "exchange": "SAFEX"},
    "KRWUSD": {"code": "K9", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "LEANHOG": {"code": "HE", "cycle": "GJKMNQVZ", "exchange": "CME"},
    "LIVECOW": {"code": "LE", "cycle": "GJMQVZ", "exchange": "CME"},
    "LUMBER-new": {"code": "LB", "cycle": "FHKNUX", "exchange": "CME"},
    # Replace MSCIASIA with EUREX symbol if available to match pysystemtrade
    #"MSCIASIA": {"code": "L5", "cycle": "HMUZ", "exchange": "ICE/US"},
    "MSCISING": {"code": "SV", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "MID-DAX": {"code": "DM", "cycle": "HMUZ", "exchange": "EUREX"},
    "MILK": {"code": "DL", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "MILKDRY": {"code": "DF", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "MILKWET": {"code": "DK", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "MILLWHEAT": {
        "code": "ML",
        "cycle": "HKUZ",
        "days_count": 900,
        "exchange": "EuronextCom",
    },
    "MSCIWORLD": {"code": "AC", "cycle": "HMUZ", "exchange": "EUREX"},
    "MXP": {"code": "M6", "cycle": "HMUZ", "exchange": "CME"},
    "MUMMY": {"code": "S.", "cycle": "HMUZ", "exchange": "JPX"},
    "NASDAQ": {"code": "NQ", "cycle": "HMUZ", "exchange": "CME"},
    "NASDAQ_micro": {"code": "NM", "cycle": "HMUZ", "exchange": "CME"},
    "NIFTY": {"code": "NH", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "NIKKEI": {"code": "NY", "cycle": "HMUZ", "exchange": "CME"},
    "NIKKEI400": {"code": "OC", "cycle": "HMUZ", "exchange": "JPX"},
    "NOK": {"code": "NR", "cycle": "HMUZ", "exchange": "CME"},
    "NZD": {"code": "N6", "cycle": "HMUZ", "exchange": "CME"},
    "OAT": {"code": "FN", "cycle": "HMUZ", "exchange": "EUREX"},
    "OATIES": {"code": "ZO", "cycle": "HKNUZ", "exchange": "CBOT"},
    "OJ": {"code": "OJ", "cycle": "FHKNUX", "exchange": "ICE/US"},
    "OMX": {"code": "FP", "cycle": "HMUZ", "exchange": "EUREX"},
    "OMXS30": {"code": "OX", "cycle": "FGHJKMNQUVXZ", "exchange": "OMX"},
    "PALLAD": {"code": "PA", "cycle": "HMUZ", "exchange": "NYMEX"},
    "PLAT": {"code": "PL", "cycle": "FJNV", "exchange": "NYMEX"},
    "PLN": {"code": "WP", "cycle": "HMUZ", "exchange": "CME"},
    "R1000": {"code": "TX", "cycle": "HMUZ", "exchange": "CME"},
    "RAPESEED": {"code": "XR", "cycle": "GKQX", "exchange": "EuronextCom"},
    "REDWHEAT": {"code": "KE", "cycle": "HKNUZ", "exchange": "KCBT"},
    "RICE": {"code": "ZR", "cycle": "FHKNUX", "exchange": "CBOT"},
    "ROBUSTA": {"code": "RM", "cycle": "FHKNUX", "exchange": "ICE/EU/Com"},
    "RUBBER": {"code": "W2", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "RUR": {"code": "R6", "cycle": "HMUZ", "exchange": "CME"},
    "RUSSELL": {"code": "QR", "cycle": "HMUZ", "exchange": "CME"},
    "SEK": {"code": "SK", "cycle": "HMUZ", "exchange": "CME"},
    "SGD_mini": {"code": "R$", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "SGX": {"code": "VS", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "SHATZ": {"code": "HF", "cycle": "HMUZ", "exchange": "EUREX"},
    "SILVER": {"code": "SI", "cycle": "FGHJKMNQUVXZ", "exchange": "COMEX"},
    "SMI": {"code": "SZ", "cycle": "HMUZ", "exchange": "EUREX"},
    "SMI-MID": {"code": "SH", "cycle": "HMUZ", "exchange": "EUREX"},
    "SOFR": {"code": "SQ", "cycle": "HMUZ", "days_count": 1100, "exchange": "CME"},
    "SONIA3": {"code": "MZ", "cycle": "HMUZ", "days_count": 1100, "exchange": "CME"},
    "SOYBEAN": {"code": "ZS", "cycle": "FHKNQUX", "exchange": "CBOT"},
    "SOYBEAN_mini": {"code": "XK", "cycle": "FHKNQUX", "exchange": "CBOT"},
    "SOYMEAL": {"code": "ZM", "cycle": "FHKNQUVZ", "exchange": "CBOT"},
    "SOYOIL": {"code": "ZL", "cycle": "FHKNQUVZ", "exchange": "CBOT"},
    "SP400": {"code": "EW", "cycle": "HMUZ", "exchange": "CME"},
    "SP500": {"code": "ES", "cycle": "HMUZ", "exchange": "CME"},
    "SP500_micro": {"code": "ET", "cycle": "HMUZ", "exchange": "CME"},
    "SPI200": {"code": "AP", "cycle": "FGHJKMNQUVXZ", "exchange": "SFE"},
    "STEEL": {"code": "HV", "cycle": "FGHJKMNQUVXZ", "exchange": "COMEX"},
    "SUGAR": {"code": "SW", "cycle": "HKQVZ", "exchange": "ICE/EU/Com"},
    "SUGAR11": {"code": "SB", "cycle": "HKNV", "days_count": 200, "exchange": "ICE/US"},
    "SWISSLEAD": {"code": "ST", "cycle": "HMUZ", "exchange": "EUREX"},
    "TECDAX": {"code": "DZ", "cycle": "HMUZ", "exchange": "EUREX"},
    "TOPIX": {"code": "TS", "cycle": "HMUZ", "exchange": "JPX"},
    "US10": {"code": "ZN", "cycle": "HMUZ", "exchange": "CBOT"},
    "US10U": {"code": "TN", "cycle": "HMUZ", "exchange": "CBOT"},
    "US2": {"code": "ZT", "cycle": "HMUZ", "exchange": "CBOT"},
    "US30": {"code": "UD", "cycle": "HMUZ", "exchange": "CBOT"},
    "US30Y": {"code": "ZB", "cycle": "HMUZ", "exchange": "CBOT"},
    "US5": {"code": "ZF", "cycle": "HMUZ", "exchange": "CBOT"},
    "US-DISCRETE": {"code": "BI", "cycle": "HMUZ", "exchange": "CME"},
    "US-ENERGY": {"code": "BM", "cycle": "HMUZ", "exchange": "CME"},
    "US-FINANCE": {"code": "BN", "cycle": "HMUZ", "exchange": "CME"},
    "US-HEALTH": {"code": "BS", "cycle": "HMUZ", "exchange": "CME"},
    "US-INDUSTRY": {"code": "JG", "cycle": "HMUZ", "exchange": "CME"},
    "US-MATERIAL": {"code": "JA", "cycle": "HMUZ", "exchange": "CME"},
    "US-PROPERTY": {"code": "BK", "cycle": "HMUZ", "exchange": "CME"},
    "US-REALESTATE": {"code": "DH", "cycle": "HMUZ", "exchange": "CBOT"},
    "US-STAPLES": {"code": "BL", "cycle": "HMUZ", "exchange": "CME"},
    "US-TECH": {"code": "JB", "cycle": "HMUZ", "exchange": "CME"},
    "US-UTILS": {"code": "JE", "cycle": "HMUZ", "exchange": "CME"},
    "US20": {"code": "ZZ", "cycle": "HMUZ", "exchange": "CBOT"},
    "US3": {"code": "ZE", "cycle": "HMUZ", "exchange": "CBOT"},
    "V2X": {"code": "DV", "cycle": "FGHJKMNQUVXZ", "exchange": "EUREX"},
    "VIX": {"code": "VI", "cycle": "FGHJKMNQUVXZ", "exchange": "CFE"},
    "VNKI": {"code": "Y.", "cycle": "FGHJKMNQUVXZ", "exchange": "JPX"},
    "WHEAT": {"code": "ZW", "cycle": "HKNUZ", "exchange": "CBOT"},
    "WHEAT_ICE": {
        "code": "LW",
        "cycle": "FHKNUX",
        "days_count": 900,
        "exchange": "ICE/EU/Com",
    },
    "WHEY": {"code": "DG", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "YENEUR": {"code": "RY", "cycle": "HMUZ", "exchange": "CME"},
    "ZAR": {"code": "T6", "cycle": "HMUZ", "exchange": "CME"},


    #New mappings added by bug-or-feature, after I added and downloaded the mappings below: 
    #The PST parquet database seems to have been cleaned. What can be done is to download the historical data for the following four: GASOILINE_ICE, MSCIEMASIA, INR and ING-SGX and add them to the parquet database. 
    "GASOILINE_ICE": {"code": "LG", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},  #note use GASOILINE_ICE to be consistent with PST  start from 2006 https://www.barchart.com/futures/quotes/LGZ25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    #- "MSCIASIA": {"code": "L5", "cycle": "HMUZ", "exchange": "ICE/US"}, #bug-or-feature correction
    #+ "MSCIEMASIA": {"code": "L5", "cycle": "M", "days_count": 1000, "exchange": "ICE/US"},
    "MSCIEMASIA": {"code": "L5", "cycle": "HMUZ", "days_count": 1000, "exchange": "ICE/US"}, #start from 2013, https://www.barchart.com/futures/quotes/L5Z25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc

    #- "INR": {"code": "U-", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"}, #bug-of-feature correction
    #+ "INR": {"code": "H3", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "INR-SGX": {"code": "U-", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"}, 
    "INR": {"code": "H3", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"}, #start from 2013 https://www.barchart.com/futures/quotes/H3V25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc


    #two more cryptos and their micros
    "SOLANA": {"code": "SA", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "SOLANA_micro": {"code": "SR", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "XRP": {"code": "SJ", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "XRP_micro": {"code": "SX", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},

    #new mappings or corrections 2025.10 
    "BARLEY": {"code": "KI", "cycle": "FGHJKMNQUVXZ", "exchange": "SFE"}, #start from 2020 https://www.barchart.com/futures/quotes/KIX25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "CNH-HK": {"code": "KX", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"}, #start from 2013 https://www.barchart.com/futures/quotes/KXV25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "COAL-RICH-BAY": {"code": "LV", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU"}, #start from 2006 https://www.barchart.com/futures/quotes/LVN25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "GBP_micro": {"code": "MB", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"}, #start from 2009 https://www.barchart.com/futures/quotes/MBZ25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    #"GBPINR": {"code": "MB", "cycle": "FGHJKMNQUVXZ", "exchange": "MCX"}, #start from 2010 https://www.barchart.com/futures/quotes/W4N25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc But this is not the same as in PST GBPINR which is traded on NSE
    "GICS-EXCESS": {"code": "G7", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"}, #start from 2014 https://www.barchart.com/futures/quotes/G7U24/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "GOLD-CN-HK": {"code": "GJ", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"}, #start from 2017 https://www.barchart.com/futures/quotes/GJV25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "GOLD-HK": {"code": "GU", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"}, #start from 2017 https://www.barchart.com/futures/quotes/GUV25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "HIBOR": {"code": "HB", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"}, #start from 1992 https://www.barchart.com/futures/quotes/HBV25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "HIGHYIELD": {"code": "OY", "cycle": "FGHJKMNQUVXZ", "exchange": "CFE"}, #
    "IG": {"code": "OG", "cycle": "FGHJKMNQUVXZ", "exchange": "CFE"}, #start from 2021 https://www.barchart.com/futures/quotes/OGZ25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "IRON-HK": {"code": "CZ", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"}, #start from 2018 https://www.barchart.com/futures/quotes/CZV25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "JPYINR": {"code": "X5", "cycle": "FGHJKMNQUVXZ", "exchange": "MCX"}, #start from 2010 https://www.barchart.com/futures/quotes/X5V25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "LEAD_LME": {"code": "R0", "cycle": "FGHJKMNQUVXZ", "exchange": "LME"}, #start from 2011  https://www.barchart.com/futures/quotes/R0V25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    'NIKKEI-SGX_mini': {'code': 'HQ', 'exchange': 'SGX', 'cycle': 'FGHJKMNQUVXZ'},  #start from 2011  https://www.barchart.com/futures/quotes/HQV25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "SILVER-mini": {"code": "QI", "cycle": "FGHJKMNQUVXZ", "exchange": "COMEX"}, # start from 2006 https://www.barchart.com/futures/quotes/QIZ25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "TIN_LME": {"code": "S4", "cycle": "FGHJKMNQUVXZ", "exchange": "LME"}, #start from 2011  https://www.barchart.com/futures/quotes/S4V25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "ZINC_LME": {"code": "O0", "cycle": "FGHJKMNQUVXZ", "exchange": "LME"}, #start from 2011  https://www.barchart.com/futures/quotes/O0V25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "FTSECHINAH": {"code": "T3", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},  #start from 2025,  Correct an earlier bc-utils error. It mapped FTSECHINAH to HA, which is the HANGENT futures. https://www.barchart.com/futures/quotes/T3V25/historical-prices?orderBy=contractExpirationDate&orderDir=asc
    "CLP": {"code": "N0", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"}, # See notion notes on CLP, correct an earlier bc-utils error. https://www.barchart.com/futures/quotes/N0X25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "EU-BANKS2": {"code": "FB", "cycle": "FGHJKMNQUVXZ", "exchange": "EUREX"}, #start from 2005 https://www.barchart.com/futures/quotes/FBZ25/historical-prices?viewName=main&orderBy=contractExpirationDate&orderDir=asc
    "NICKEL_LME": {"code": "Q0", "cycle": "FGHJKMNQUVXZ", "exchange": "LME"},
    "EU-CHEM": {"code": "DLS", "cycle": "HMUZ", "exchange": "EUREX"}, # correct an earlier bc-utils error https://www.barchart.com/futures/quotes/DLSZ25/futures-prices?viewName=main
    "EU-DJ-CHEM": {"code": "C1", "cycle": "HMUZ", "exchange": "EUREX"}, # correct an earlier bc-utils error, this was mistaken for EU-DJ-CHEM earlier
    "EU-TELECOM": {"code": "J5", "cycle": "HMUZ", "exchange": "EUREX"}, #correct an earlier bc-utils error, this was mistaken for EU-DJ-TELECOM
    "EU-DJ-TELECOM": {"code": "L9", "cycle": "HMUZ", "exchange": "EUREX"}, #correct an earlier bc-utils error, this is the true EU-DJ-TELECOM
    "EUROSTX-MID": {"code": "PG", "cycle": "HMUZ", "exchange": "EUREX"}, #correct an earlier bc-utils error, this was mistaken as EU-MID
    "EU-MID": {"code": "FM", "cycle": "HMUZ", "exchange": "EUREX"}, #correct an earlier bc-utils error, this is EU-MID
    

    ##From 2024 config_old
    'AUD_micro': {'code': 'MG', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'AUSCASH': {'code': 'IQ', 'exchange': 'SFE', 'cycle': 'FGHJKMNQUVXZ'}, 'CORRA': {'code': 'RG', 'exchange': 'TMX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'BITCOIN-LARGE': {'code': 'BT', 'cycle': 'FGHJKMNQUVXZ', 'exchange': 'CME'}, 
    'CAD2': {'code': 'CH', 'exchange': 'TMX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'CAD5': {'code': 'GM', 'exchange': 'TMX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'CHINAA-CON': {'code': 'D1', 'exchange': 'HKFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'COAL-GEORDIE': {'code': 'LQ', 'exchange': 'ICE/EU', 'cycle': 'FGHJKMNQUVXZ'}, 
    'COAL': {'code': 'LU', 'exchange': 'ICE/EU', 'cycle': 'FGHJKMNQUVXZ'}, 
    'COPPER_LME': {'code': 'O9', 'exchange': 'LME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'COPPER-mini': {'code': 'QC', 'exchange': 'COMEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'CORN_mini': {'code': 'XN', 'exchange': 'CBOT', 'days_count': 700, 'cycle': 'FGHJKMNQUVXZ'}, 
    'CRUDE_W_micro': {'code': 'CY', 'exchange': 'NYMEX', 'days_count': 500, 'cycle': 'FGHJKMNQUVXZ'}, 
    'CRUDE_W_mini': {'code': 'QM', 'exchange': 'NYMEX', "days_count": 500,'cycle': 'FGHJKMNQUVXZ'}, 
    'EDOLLAR': {'code': 'GE', 'cycle': 'HMUZ', 'days_count': 1100, 'exchange': 'CME'}, 
    'ETHANOL-CHICAGO': {'code': 'FL', 'cycle': 'FGHJKMNQUVXZ', 'exchange': 'NYMEX'}, 
    'ETHER-MICRO': {'code': 'TA', 'cycle': 'FGHJKMNQUVXZ', 'exchange': 'CME'}, 
    'EUR_mini': {'code': 'E7', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'EUR_micro': {'code': 'MF', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'FTSE100-DIV': {'code': 'IB', 'exchange': 'ICE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'GASOILINE_micro': {'code': 'FR', 'exchange': 'NYMEX', 'days_count': 900, 'cycle': 'FGHJKMNQUVXZ'}, 
    'GOLD-mini': {'code': 'QO', 'exchange': 'COMEX', 'days_count': 800, 'cycle': 'FGHJKMNQUVXZ'}, 
    'HANGENT': {'code': 'HA', 'exchange': 'HKFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'HANG_mini': {'code': 'HK', 'exchange': 'HKFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'HSCEI-DIV': {'code': 'E$', 'exchange': 'HKFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'IBEX_mini': {'code': 'EZ', 'cycle': 'HMUZ', 'exchange': 'MEFF'}, 
    'JPY_mini': {'code': 'J7', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MSCIEAFA': {'code': 'DI', 'exchange': 'ICE/US', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MSCIBRAZIL': {'code': 'F5', 'exchange': 'ICE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MSCICHINA': {'code': 'NA', 'exchange': 'EUREX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MSCIEM-LIFFE': {'code': 'DE', 'exchange': 'ICE/US', 'cycle': 'FGHJKMNQUVXZ'}, 
    'NIKKEI-JPY': {'code': 'NL', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'NIKKEI-SGX': {'code': 'NX', 'exchange': 'SGX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'NIKKEI-SGX-DIV': {'code': 'HT', 'exchange': 'SGX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'NIKKEI_large': {'code': 'NO', 'exchange': 'JPX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'SARONA': {'code': 'J2', 'cycle': 'HMUZ', 'days_count': 1100, 'exchange': 'ICE'}, 
    'SONIA3-ICE': {'code': 'J8', 'cycle': 'HMUZ', 'days_count': 1100, 'exchange': 'ICE'}, 
    'SOFR1': {'code': 'SL', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'SP500_mini': {'code': 'EY', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'SUGAR16': {'code': 'SD', 'exchange': 'ICE/US', 'days_count': 700, 'cycle': 'FGHJKMNQUVXZ'}, 
    'THB': {'code': 'W.', 'exchange': 'SGX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'TSE60': {'code': 'TP', 'exchange': 'TMX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'UMBS-50': {'code': 'BUT', 'exchange': 'CBOT', 'cycle': 'FGHJKMNQUVXZ'}, 
    'US10Y_micro': {'code': 'TO', 'exchange': 'CBOT', 'cycle': 'FGHJKMNQUVXZ'}, 
    'USDCAD_micro': {'code': 'WK', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'USDCHF_micro': {'code': 'WN', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    'USDCNH-CME': {'code': 'H5', 'exchange': 'CME', 'cycle': 'FGHJKMNQUVXZ'}, 
    #'USDCNH-HK': {'code': 'KX', 'exchange': 'HKFE', 'cycle': 'FGHJKMNQUVXZ'},  #USDCNH-HK is not on BarChart, but CNH-HK is. USDCNH-HK is CNH-HK's mini contract https://www.hkex.com.hk/Products/Listed-Derivatives/Foreign-Exchange/USD-CNH-Futures?sc_lang=en
    'USDCNH-SGX_mini': {'code': 'I$', 'exchange': 'SGX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'VIX_mini': {'code': 'VJ', 'exchange': 'CFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'WHEAT_mini': {'code': 'XW', 'exchange': 'CBOT', 'days_count': 500, 'cycle': 'FGHJKMNQUVXZ'}, 
    
    
    
    'MT-CFFEX-30Y': {'code': 'U!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-10Y': {'code': 'O!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-5Y': {'code': 'P!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-2Y': {'code': 'T!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-SSE50': {'code': 'R!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-CSI300': {'code': 'S!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-CSI500': {'code': 'Q!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-CFFEX-CSI1000': {'code': 'W!', 'exchange': 'CFFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-TAIFEX-TWI': {'code': 'TW', 'exchange': 'TAIFEX', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-BMF-BOVESPA': {'code': 'XI', 'exchange': 'BM&F Bovespa', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-BMF-BOVESPA-MINI': {'code': 'UM', 'exchange': 'BM&F Bovespa', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-BMF-BRLUSD': {'code': 'XD', 'exchange': 'BM&F Bovespa', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-ASX-90D': {'code': 'IR', 'exchange': 'SFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-ASX-3Y': {'code': 'YT', 'exchange': 'SFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-ASX-10Y': {'code': 'YU', 'exchange': 'SFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-ASX-FIN-X-REIT': {'code': 'V6', 'exchange': 'SFE', 'cycle': 'FGHJKMNQUVXZ'}, 
    'MT-ASX-EASTERNWHEAT': {'code': 'X9', 'exchange': 'SFE', 'cycle': 'FGHJKMNQUVXZ'}
    
}


# source: https://www.barchart.com/solutions/data/futures
EXCHANGES = {
    "CBOT": {"tick_date": "2008-05-04", "eod_date": "1978-03-03"},
    "CFE": {"tick_date": "2009-11-24", "eod_date": "2004-04-02"},
    "CME": {"tick_date": "2008-05-05", "eod_date": "1978-03-23"},
    "COMEX": {"tick_date": "2008-05-04", "eod_date": "1978-02-27"},
    "ENDEX": {"tick_date": "2014-01-01", "eod_date": "2014-01-01"},
    "EUREX": {"tick_date": "1999-06-23", "eod_date": "1990-11-28"},
    "EuronextCom": {"tick_date": "2011-05-25", "eod_date": "2001-09-17"},
    "EuronextInd": {"tick_date": "2011-05-25", "eod_date": "2003-06-23"},
    "HKFE": {"tick_date": "2008-05-05", "eod_date": "1986-05-06"},
    "ICE": {"tick_date": "2008-05-04", "eod_date": "1978-08-07"},
    "ICE/CA": {"tick_date": "2008-05-04", "eod_date": "1979-01-23"},
    "ICE/EU/Com": {"tick_date": "2008-05-05", "eod_date": "1989-07-24"},
    "ICE/EU/Fin": {"tick_date": "1999-06-21", "eod_date": "1982-11-04"},
    "ICE/SG": {"tick_date": "2010-03-09", "eod_date": "2010-03-09"},
    "ICE/US": {"tick_date": "2008-05-04", "eod_date": "1978-08-07"},
    "LME": {"tick_date": "2008-05-05", "eod_date": "2011-12-16"},
    "JPX": {"tick_date": "1992-01-06", "eod_date": "1992-01-06"},
    "KCBT": {"tick_date": "2008-07-14", "eod_date": "1979-03-26"},
    "MEFF": {"tick_date": "1992-09-29", "eod_date": "1992-09-29"},
    "NYMEX": {"tick_date": "2008-05-05", "eod_date": "1978-05-15"},
    "OMX": {"tick_date": "2012-01-27", "eod_date": "2012-01-27"},
    "SAFEX": {"tick_date": "2004-01-02", "eod_date": "2004-01-02"},
    "SFE": {"tick_date": "2019-11-03", "eod_date": "1980-01-02"},
    "SGX": {"tick_date": "2008-05-05", "eod_date": "1986-09-03"},
    "TMX": {"tick_date": "2010-04-05", "eod_date": "1993-04-22"},


    #added 2025-10
    "MCX": {"tick_date": "2010-01-01", "eod_date": "2010-01-01"},
    'ICE/EU' : {"tick_date": "2008-05-04", "eod_date": "1978-08-07"},
    'Euronext' : {"tick_date": "2011-05-25", "eod_date": "2001-09-17"},
    'CFFEX': {"tick_date": "2030-01-01", "eod_date": "2015-12-14"}, #No tick data
    'TAIFEX': {"tick_date": "2030-01-01", "eod_date": "1993-03-29"}, #No tick data
    'BM&F Bovespa': {"tick_date": "2011-10-06", "eod_date": "2002-04-15"}, 

}
