barchart_username: 'tang.eric.ht@gmail.com'
barchart_password: 'cdefgh12'
barchart_path: '/mnt/sda1/data/barchart2025'
barchart_download_list:
  - BITCOIN
  - CHFJPY
barchart_update_list:
  - BITCOIN
  - CHFJPY
barchart_start_year: 2000
barchart_end_year: 2023
barchart_dry_run: True
barchart_do_daily: True
